env: "sc2v2"

env_args:
  map_name: null
  time_limit: 150

test_greedy: True
test_nepisode: 100
test_interval: 20000
log_interval: 20000
runner_log_interval: 20000
learner_log_interval: 20000
t_max: 4050000
